##                                                                                    
##  Makefile -- Build procedure for sample logout_cas Apache module                   
##  Autogenerated via ``apxs -n logout_cas -g''.                                      
##                                                                                    
                                                                                      
builddir=.                                                                            
top_srcdir=/usr/local/apache2                                                         
top_builddir=/usr/local/apache2                                                       
include /usr/local/apache2/build/special.mk                                           
                                                                                      
#   the used tools                                                                    
APXS=apxs                                                                             
APACHECTL=apachectl                                                                   
                                                                                      
#   additional defines, includes and libraries                                        
#DEFS=-Dmy_define=my_value                                                            
#INCLUDES=-Imy/include/dir                                                            
#LIBS=-Lmy/lib/dir -lmylib                                                            
                                                                                      
#   the default target                                                                
all: local-shared-build                                                               
                                                                                      
#   install the shared object file into Apache                                        
install: install-modules-yes                                                          
                                                                                      
#   cleanup                                                                           
clean:                                                                                
        -rm -f mod_logout_cas.o mod_logout_cas.lo mod_logout_cas.slo mod_logout_cas.la
                                                                                      
#   simple test                                                                       
test: reload                                                                          
        lynx -mime_header http://localhost/logout                            
                                                                                      
#   install and activate shared object by reloading Apache to                         
#   force a reload of the shared object file                                          
reload: install restart                                                               
                                                                                      
#   the general Apache start/restart/stop                                             
#   procedures                                                                        
start:                                                                                
        $(APACHECTL) start                                                            
restart:                                                                              
        $(APACHECTL) restart                                                          
stop:                                                                                 
        $(APACHECTL) stop                                                             